# Generated by Django 5.0.1 on 2024-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=12)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
